### ISSUE TITLE
多线程下载时，单一线程出现问题会导致任务下载异常

### ISSUE THREAD

**Issue by nichbar** [qinweiforandroid/QDownload#1]
你好，感谢分享这个简单易读的多线程下载库

翻阅代码时发现了一些问题

代码可见

https://github.com/qinweiforandroid/QDownload/blob/8a249436f96bfc05e485553cc561dee4e16159f3/download/src/main/java/com/qw/download/DownloadTask.java#L252

当下载线程 `DownloadThread` 抛出异常(错误)时，在`DownloadTask`进行重试，但下载重试时忽略了当前正在进行运行中的线程，会出现线程错乱问题

**Comment by qinweiforandroid** [comment]
`DownloadTask` 254 行 `threads[i].cancelByError();` 会停止下载的线程

**Comment by nichbar** [comment]
My bad，没有留意到这一行

不过似乎还是有一些隐藏的问题，如果多线程下载时下载源只支持同时建立 4 个连接，而我们的多线程数量配置是 5 个的话，那么最后一个线程就会因为连接失效让整个下载任务异常

**Comment by qinweiforandroid** [comment]
这种场景由开发者自行控制就好了吧，框架是不知道 下载源只支持建立几个连接。据我了解http通讯协议响应header也没有此数据定义
