### ISSUE TITLE
下载过大文件异常

### ISSUE THREAD

**Issue by nichbar** [qinweiforandroid/QDownload#2]
https://github.com/qinweiforandroid/QDownload/blob/8a249436f96bfc05e485553cc561dee4e16159f3/download/src/main/java/com/qw/download/DownloadTask.java#L124-L125

整型最大的值是 2147483647，从 byte 换算成 gigabyte 也就是 2.14G，这里如果用整型的话当文件大小大于 2.14G 的时候就会出现问题

**Comment by qinweiforandroid** [comment]
已修复
