### ISSUE TITLE
能否开放自定义文件下载目录以及自定义下载文件名称？

### ISSUE THREAD

**Issue by QYC5535** [qinweiforandroid/QDownload#4]
能否开放自定义文件下载目录以及自定义下载文件名称？

**Comment by qinweiforandroid** [comment]
`DownloadTask 39行 ` 构建了下载路径，具体逻辑看`genDestFile`函数
只需在构建下载任务的时候指定 `DownloadEntry中downloadDir、fileName` 即可

**Comment by qinweiforandroid** [comment]
> 能否开放自定义文件下载目录以及自定义下载文件名称？

`DownloadTask 39行 ` 构建了下载路径，具体逻辑看`genDestFile`函数
只需在构建下载任务的时候指定 `DownloadEntry中downloadDir、fileName` 即可
