### ISSUE TITLE
How to add custom Header ?

### ISSUE THREAD

**Issue by depezo** [qinweiforandroid/QDownload#6]
I use a site that requires personalized headers, in the description you mention the possibility of adding a custom header, but I cannot do it.

**Comment by qinweiforandroid** [comment]
Yes, it is not supported at present. I will consider supporting the next version. At the same time, I plan to use okhttp to complete the download work.发自我的 iPhone在 2023年9月13日，15:34，depezo ***@***.***> 写道：﻿
I use a site that requires personalized headers, in the description you mention the possibility of adding a custom header, but I cannot do it.

**Comment by qinweiforandroid** [comment]
@depezo HI.   new version is support  custom Header  version:3.0.1120.   you can see MyApplication class
